version: '3.8'

services:
  web_api:
    build:
      context: .
    hostname: web_api
    container_name: web_api
    env_file: ./.env
    command: bash -c "python run_api.py"
    volumes:
      - ./:/app/
  update_parser:
    build:
      context: .
    hostname: update_parser
    container_name: update_parser
    env_file: ./.env
    command: bash -c "python run_parser.py"
    volumes:
      - ./:/app/
  nginx_container:
    image: nginx:1.25.3
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app/
    depends_on:
      - web_api
volumes:
  redis_broker_volume:
