"""migrations

Revision ID: b7e5e3977d3c
Revises: 5bc36d5babad
Create Date: 2023-11-28 14:12:35.228143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e5e3977d3c'
down_revision: Union[str, None] = '5bc36d5babad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Title', sa.Column('last_episode', sa.Float(), nullable=True))
    op.drop_column('Title', 'binary_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Title', sa.Column('binary_image', sa.TEXT(), nullable=True))
    op.drop_column('Title', 'last_episode')
    # ### end Alembic commands ###
